### ISSUE TITLE
The links should parse XML data format link <CData /> when parsing sitemaps

### ISSUE THREAD

**Issue by naveensky** [sromexs/get-sitemap-links#2]
First of all, thanks for your work here :) 

I am using this library for an internal tool and realized that this fails to extract URLs correctly when the loc data is in CDAta format like below 

```
<sitemap>
  <loc><![CDATA[https://example.com/post-sitemap.xml]]></loc>
  <lastmod><![CDATA[2020-11-16T18:13:33+00:00]]></lastmod>
</sitemap>
```

In this case, the expected return value is `https://example.com/post-sitemap.xm` but instead we get `<![CDATA[https://example.com/post-sitemap.xml]]>`

We perhaps need to add a regex somewhere to extract data between CData section

**Comment by sromexs** [comment]
bro this is dead package use your own code for solving this issue

**Comment by naveensky** [comment]
@sromexs - thanks for clarifying, I didn't realize this was dead. I think perhaps updating the readme file about the status of the code will help developers like me. 

Thanks for the work still, helped me save time in my dev
